export const ROUTES = {
  INITIAL_SPLASH: "InitialSplash",
  PRE_LOGIN: "PreLogin",
  LOGIN: "Login",
  FORGOT_PASSWORD: "ForgotPassword",
  RESET_PASSWORD: "ResetPassword",
  REGISTER: "Register",
  REGISTRATION_SUCCESS: "RegistrationSuccess",
  POST_AUTH_SPLASH: "PostAuthSplash",
  MAIN_APP: "MainApp",
  IN_APP_BROWSER: "InAppBrowser",
  PERSONAL_PROFILE: "PersonalProfile",
  PROFILE_INFO: "ProfileInfo",
  EDIT_PERSONAL_INFO: "EditPersonalInfo",
  SETTINGS: "Settings",
  ACCOUNT_SETTINGS: "AccountSettings",
  CHANGE_PASSWORD: "ChangePassword",
  DEACTIVATE_ACCOUNT: "DeactivateAccount",
  ORGANIZATION_ABOUT: "OrganizationAbout",
  MORE: "more",
};
